name: GitHub Output
on: push
jobs:
  share: 
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello World" >> ${GITHUB_OUTPUT}
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "The result is ${RESULT}"