name: Literals
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 1234 }}
          LITERAL_STRING: ${{ "This is a final test" }}
          LITERAL_OMIT_STRING: ${{ "This is the last test" }}
         